export const TECH_LINKS = {
  "AWS Lambda": "https://aws.amazon.com/lambda/",
  "AWS SQS": "https://aws.amazon.com/sqs/",
  Django: "https://www.djangoproject.com/",
  "Spring Boot": "https://spring.io/projects/spring-boot",
  SVG: "https://developer.mozilla.org/en-US/docs/Web/SVG",
  CSS: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  Motion: "https://motion.dev/",
  "ASP.NET Core": "https://dotnet.microsoft.com/apps/aspnet",
  Alembic: "https://alembic.sqlalchemy.org/",
  AWS: "https://aws.amazon.com/",
  Celery: "https://docs.celeryq.dev/",
  Docker: "https://www.docker.com/",
  "Express.js": "https://expressjs.com/",
  FastAPI: "https://fastapi.tiangolo.com/",
  Go: "https://go.dev/",
  Grafana: "https://grafana.com/",
  "GitHub Actions": "https://github.com/features/actions",
  Java: "https://dev.java/",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  Kubernetes: "https://kubernetes.io/",
  LangChain: "https://www.langchain.com/",
  LangGraph: "https://langchain-ai.github.io/langgraph/",
  MongoDB: "https://www.mongodb.com/",
  Mongoose: "https://mongoosejs.com/",
  "Node.js": "https://nodejs.org/",
  PostgreSQL: "https://www.postgresql.org/",
  Prometheus: "https://prometheus.io/",
  PyTorch: "https://pytorch.org/",
  Pydantic: "https://docs.pydantic.dev/",
  Python: "https://www.python.org/",
  React: "https://react.dev/",
  Redis: "https://redis.io/",
  Redux: "https://redux.js.org/",
  SQL: "https://www.postgresql.org/docs/current/sql.html",
  SQLAlchemy: "https://www.sqlalchemy.org/",
  "Tailwind CSS": "https://tailwindcss.com/",
  TypeScript: "https://www.typescriptlang.org/",
  WebSocket: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
  pgvector: "https://github.com/pgvector/pgvector",
  pytest: "https://docs.pytest.org/",
} as const;
